framework:
    workflows:
        mfc_request:
            type: 'state_machine'
            marking_store:
                type: 'method'
                property: 'state'
            supports: [App\Entity\MfcRequest]
            initial_marking: step1
            places: [step1, step2, done]
            transitions:
                to_step2: { from: step1, to: step2 }
                back_to_step1: { from: step2, to: step1 }
                finish: { from: step2, to: done }
