framework:
    workflows:
        mfc_request:
            type: 'state_machine'
            marking_store:
                type: 'method'
                property: 'state'
            supports: [App\Entity\MfcRequest]
            initial_marking: step1
            places: [step1, step2, step3, done]
            transitions:
                to_step2: { from: step1, to: step2 }
                to_step3: { from: [step1, step2], to: step3 }
                back_to_step1: { from: [step2, step3], to: step1 }
                back_to_step2: { from: step3, to: step2 }
                finish: { from: [step1, step2, step3], to: done }
