# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    mfc_upload_dir: '%kernel.project_dir%/var/uploads/mfc'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    App\Controller\ErrorController:
        tags: ['controller.service_arguments']

    GuzzleHttp\Client:
        arguments:
            $config:
                timeout: 30
                connect_timeout: 5

    Psr\Http\Client\ClientInterface: '@GuzzleHttp\Client'

    App\Service\Cache\EmailOtpStorageService:
        arguments:
            $adapter: '@cache.app'

    App\Service\OtpGenerator:
        arguments:
            $length: 6

    App\Service\Communication\EmailSender:
        arguments:
            $fromEmail: '%env(MAIL_FROM_EMAIL)%'
            $supportEmail: '%env(MAIL_SUPPORT_EMAIL)%'
            $fromName: '%env(MAIL_FROM_NAME)%'

    app.http_client.mfc_api:
        class: GuzzleHttp\Client
        arguments:
            $config:
                timeout: 50
                connect_timeout: 50

    App\Service\MfcApiClient:
        arguments:
            $httpClient: '@app.http_client.mfc_api'
            $baseUrl: '%env(MFC_API_BASE_URL)%'
            $apiKey: '%env(MFC_API_KEY)%'
            $username: '%env(MFC_API_USERNAME)%'
            $password: '%env(MFC_API_PASSWORD)%'

    App\Service\MfcFileStorage:
        arguments:
            $uploadDir: '%mfc_upload_dir%'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

when@test:
    services:
        _defaults:
            public: true  # Make services public in test env
